<!doctype html>
<html lang="en">

<head>
    <#--    <@boot.importBootstrap />-->
    <#--    <@hf.headForHeaderAndFooter />-->
    <#--    <@form.headForInputForm />-->
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>моай</title>
    <#--    <title><@spring.message 'ad' /></title>-->
</head>
<body>
<button><a href="https://oauth.vk.com/authorize?client_id=7943922&display=page&redirect_uri=http://localhost:8080/vk/signIn&scope=groups,photos,offline&response_type=code&v=5.131">Авторизация VK</a></button>
</body>
</html>